# Generated by Django 4.1.5 on 2023-04-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('smail', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('secondary_institute', models.CharField(max_length=100)),
                ('secondary_score', models.CharField(max_length=100)),
                ('higher_institute', models.CharField(max_length=100)),
                ('higher_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Uid', models.IntegerField(primary_key=True, serialize=False)),
                ('AdminMail', models.CharField(max_length=100)),
                ('pswd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='C_Academics',
            fields=[
                ('university_name', models.CharField(max_length=100)),
                ('b_name', models.CharField(max_length=100)),
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('cgpa', models.IntegerField()),
                ('attendance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('Cer1Name', models.CharField(max_length=100)),
                ('Cer1', models.ImageField(upload_to='certificate')),
                ('Cer2Name', models.CharField(max_length=100)),
                ('cer2', models.ImageField(upload_to='certificate')),
                ('Cer3Name', models.CharField(max_length=100)),
                ('cer3', models.ImageField(upload_to='certificate')),
                ('Cer4Name', models.CharField(max_length=100)),
                ('cer4', models.ImageField(upload_to='certificate')),
                ('Cer5Name', models.CharField(max_length=100)),
                ('cer5', models.ImageField(upload_to='certificate')),
            ],
        ),
        migrations.CreateModel(
            name='Govt_Doc',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('Adhar_Num', models.IntegerField()),
                ('Adhar_Doc', models.ImageField(upload_to='Adhar_Doc')),
                ('Pan_Num', models.CharField(max_length=100)),
                ('Pan_Doc', models.ImageField(upload_to='Pan_Doc')),
                ('Votter_num', models.CharField(max_length=100)),
                ('Votter_Doc', models.ImageField(upload_to='Votter_Doc')),
                ('Caste_id', models.CharField(max_length=100)),
                ('Caste_Doc', models.ImageField(upload_to='Caste_Doc')),
            ],
        ),
        migrations.CreateModel(
            name='Personaldetails',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField()),
                ('mail_id', models.CharField(max_length=100)),
                ('Father_name', models.CharField(max_length=100)),
                ('Father_prof', models.CharField(max_length=100)),
                ('Mother_name', models.CharField(max_length=100)),
                ('Mother_prof', models.CharField(max_length=100)),
                ('current_add', models.TextField()),
                ('permanent_add', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TempPersonaldetails',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_no', models.IntegerField()),
                ('Father_prof', models.CharField(max_length=100)),
                ('Mother_prof', models.CharField(max_length=100)),
                ('current_add', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TNP',
            fields=[
                ('Uid', models.IntegerField()),
                ('Bid', models.IntegerField()),
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_credit', models.CharField(max_length=100)),
                ('course_score', models.CharField(max_length=100)),
                ('aicte_approv', models.BooleanField(default=False)),
                ('catagory', models.CharField(max_length=100)),
                ('certificate', models.ImageField(upload_to='certificate')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('Uid', models.IntegerField(primary_key=True, serialize=False)),
                ('UName', models.CharField(max_length=100)),
                ('BName', models.CharField(max_length=100)),
                ('UserMail', models.CharField(max_length=100)),
                ('pswd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UploaderCert',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('Uid', models.IntegerField()),
                ('University_name', models.CharField(max_length=100)),
                ('Student_name', models.CharField(max_length=100)),
                ('Course_name', models.CharField(max_length=100)),
                ('Course_credit', models.IntegerField()),
                ('score', models.IntegerField()),
                ('Aicte_app', models.BooleanField(default=False)),
                ('certi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UploaderCredential',
            fields=[
                ('U_mail', models.CharField(max_length=100)),
                ('Uid', models.IntegerField(primary_key=True, serialize=False)),
                ('pswd', models.CharField(max_length=100)),
                ('institute_name', models.CharField(max_length=100)),
                ('R1', models.BooleanField(default=False)),
                ('R2', models.BooleanField(default=False)),
                ('tellaboutself', models.TextField()),
            ],
        ),
    ]
